services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "10923:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data: