name: CD Bad Ice Cream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: pnpm install, build and test
        run: |
          pnpm install
          pnpm prisma:generate
          pnpm run build
          pnpm run test
      
      - name: Prisma Migrate
        env: 
          DB_URI: ${{ secrets.DB_URI_PROD }}
          DB_DIRECT_URL: ${{ secrets.DB_DIRECT_URL_PROD }}
          DB_USER: ${{ secrets.DB_USER_PROD }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
          DB_NAME: ${{ secrets.DB_NAME_PROD }}
        run: pnpm prisma:migrate:deploy

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bad-ice-cream-back'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F2CC811A03E471D8ED2DB8533CA02F6 }}
          clean: true
